name = 'アリメクタ "Alimektor" アレネクト'

[[links]]
name = "Telegram"
badge = "Telegram-2CA5E0?style=for-the-badge&logo=telegram&logoColor=white"
url = "https://t.me/alimektor"

[[links]]
name = "Gmail"
badge = "Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white"
url = "mailto:alimektor@gmail.com?subject=%5BGitHub%5D%20SUBJECT&body=Hello%2C%20Alimektor%0D%0A%0D%0A1.%20WHO%20ARE%20YOU.%0D%0A2.%20WHAT%20YOU%20NEED.%0D%0A3.%20YOUR%20QUESTION%20OR%20OFFER.%0D%0A4.%20YOUR%20EXPECTATIONS."
