---
name: Update README

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 23 * * 0'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.PERSONAL_TOKEN }}" | gh auth login --with-token

      - name: Make script executable
        run: chmod +x run.py

      - name: Run the script
        run: ./run.py

      - name: Commit and push changes
        run: |
          git config --local user.name "アリメクタ アレネクト"
          git config --local user.email "alimektor@gmail.com"
          git diff-index --quiet HEAD -- || sed -i "s/Last Updated: DATE_HERE/Last Updated: $(date +"%B %d, %Y")/" README.md
          git add .
          git commit -m "Update README from Github Actions task" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
